language: ruby
rvm:
- 2.2.5
sudo: false
script: bundle exec rake deploy
env:
  global:
    secure: ULIR3c85wLNstv1DbBQPYh0MNS9UsZx18WpBGVzBmrwELxFsPa2nKU1aOY2NXzkgyVqPLfk5F5wEkaq+oFzJnKxqkoatA2HrghcLMawhk+vIutlXR/oq5nqez78J+OKOAx0/OrePH23Qtj9B5i+11+lBu7S3cUKi/fiM+E5OK0Sq9zWYX6J1jY6enqEZhGqrTVQErBDPsjAW9ID6ox2EasFZhz/hXSrtN8rURKkRVSI6d2fF6WHujLRoIVK9JjDGOHKma6V7qxSGhtNmoYDFwS23opfDyWo9hJgnO9LIc7+aaPpJfBI7lRMUAz5FIirb0WJ46p309AlKKv08i836IetPNPBv+CTopTkQoI5KKHyY1mRgTbypnpG0pzPSLfZ3YhhFtCWNiniZOc7w45VsWjJTHS4X5JfkJnkEO7XCCyiVMdi4pQnJaFpZpyqFSRJ7BYdJvd1zaLetjUMO2a0aUJ/xOBJq17MYSGvKx9IIvgabhZVXcaqZUqEy33KAdmpdcl/6rshSlHTtX2hvSSHygHz9pr3+PxM3cefDq9HfDP10rnIfPoh6+mk3WJxG8f2YLA7s6w2N61DnPS3cgy/aY/IiiVWatG4pFohqS/qSg1GKhJxYRfVaW5k+/8F61LBF2yDQp5WbAzInUE2/U/lEBwcHzwPK5Ru/wZo9anvRk58=
